inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0


# 日本語のコメントを OK とする
Style/AsciiComments:
  Enabled: false

# 一行に 120 文字まで書いても OK とする
#Metrics/LineLength:
#  Max: 120
Layout/LineLength:
  Max: 120

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

# frozen_string_literal: trueが付かないようにする
Style/FrozenStringLiteralComment:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: 'snake_case'

Style/Documentation:
  Enabled: true

#  Department:
#    Enabled: false # 無効にする
#    # Severity: warning # 警告レベルを下げる (デフォルトはerror)

